local_repository(
    name = "rules_booking",
    path = "../../",
)

load(
    "@rules_booking//booking:repositories.bzl",
    "repositories",
)

repositories()

load(
    "@rules_booking//booking:dependencies.bzl",
    "dependencies",
)

dependencies()

load(
    "@rules_booking//dev:repositories.bzl",
    _dev_dependencies = "dependencies",
)

_dev_dependencies()
