"rules_booking dependencies"

module(
    name = "rules_booking",
    version = "0.0.1",
)

bazel_dep(name = "bazel_skylib", version = "1.9.0")
bazel_dep(name = "rules_pkg", version = "1.2.0")

extra_dependencies = use_extension("//booking:module.bzl", "extra_dependencies")
use_repo(
    extra_dependencies,
    "bazel_version",
)

bazel_dep(name = "buildifier_prebuilt", version = "8.5.1.2", dev_dependency = True)

dev_dependencies = use_extension("//dev:module.bzl", "extra_dev_dependencies", dev_dependency = True)
use_repo(
    dev_dependencies,
    "rules_java_7_9_0",
)

bazel_dep(name = "aspect_gazelle_prebuilt", version = "0.0.11", dev_dependency = True)
