name: "build and test"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  # Cancel previous actions from the same PR or branch except 'main' branch.
  # See https://docs.github.com/en/actions/using-jobs/using-concurrency and https://docs.github.com/en/actions/learn-github-actions/contexts for more info.
  group: concurrency-group::${{ github.workflow }}::${{ github.event.pull_request.number > 0 && format('pr-{0}', github.event.pull_request.number) || github.ref_name }}${{ github.ref_name == 'main' && format('::{0}', github.run_id) || ''}}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: bazel-contrib/setup-bazel@0.8.5
      with:
        # we don't release often to make use of caches
        bazelisk-cache: false
        disk-cache: false
        repository-cache: false
        external-cache: false
    - run: |
        set -ex
        bazelisk build //... && bazelisk test //...
        bazelisk run //:gazelle && git status --porcelain

  e2e-bzlmod-matrix:
    strategy:
      matrix:
        version: [7.x, 8.x, 9.x]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: bazel-contrib/setup-bazel@0.8.5
      with:
        # we don't release often to make use of caches
        bazelisk-cache: false
        disk-cache: false
        repository-cache: false
        external-cache: false
    - run: |
        set -ex
        cd e2e/bzlmod
        export USE_BAZEL_VERSION=${{ matrix.version.version }}
        bazelisk build //...
        bazelisk test //...
